/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc4380;

import java.awt.event.ActionListener;

/**
 *
 * @author aaron
 */
public class View extends javax.swing.JFrame {


    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_user = new javax.swing.JPanel();
        panel_converter = new javax.swing.JPanel();
        panel_convert_input = new javax.swing.JPanel();
        leftAmount = new javax.swing.JTextField();
        leftSymbol = new javax.swing.JLabel();
        leftDropDown = new javax.swing.JComboBox<>();
        panel_convert_output = new javax.swing.JPanel();
        rightAmount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rightDropDown = new javax.swing.JComboBox<>();
        panel_convert_buttons = new javax.swing.JPanel();
        button_swap = new javax.swing.JButton();
        button_covert = new javax.swing.JButton();
        button_clear = new javax.swing.JButton();
        panel_history = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItem_Exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout panel_userLayout = new javax.swing.GroupLayout(panel_user);
        panel_user.setLayout(panel_userLayout);
        panel_userLayout.setHorizontalGroup(
            panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        panel_userLayout.setVerticalGroup(
            panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("User", panel_user);

        panel_converter.setBackground(new java.awt.Color(32, 0, 96));

        panel_convert_input.setBackground(new java.awt.Color(32, 0, 96));

        leftSymbol.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        leftSymbol.setForeground(new java.awt.Color(255, 255, 255));
        leftSymbol.setText("$");

        leftDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentine Peso", "Australian Dollar", "Bahraini Dinar", "Botswana Pula", "Brazilian Real", "British Pound", "Bruneian Dollar", "Bulgarian Lev", "Canadian Dollar", "Chilean Peso", "Chinese Yuan Renminbi", "Colombian Peso", "Croatian Kuna", "Czech Koruna", "Danish Krone", "Emirati Dirham", "Euro", "Hong Kong Dollar", "Hungarian Forint", "Icelandic Krona", "Indian Rupee", "Indonesian Rupiah", "Iranian Rial", "Israeli Shekel", "Japanese Yen", "Kazakhstani Tenge", "Kuwaiti Dinar", "Libyan Dinar", "Malaysian Ringgit", "Mauritian Rupee", "Mexican Peso", "Nepalese Rupee", "New Zealand Dollar", "Norwegian Krone", "Omani Rial", "Pakistani Rupee", "Philippine Peso", "Polish Zloty", "Qatari Riyal", "Romanian New Leu", "Russian Ruble", "Saudi Arabian Riyal", "Singapore Dollar", "South African Rand", "South Korean Won", "Sri Lankan Rupee", "Swedish Krona", "Swiss Franc", "Taiwan New Dollar", "Thai Baht", "Trinidadian Dollar", "Turkish Lira", "US Dollar", "Venezuelan Bolivar" }));

        javax.swing.GroupLayout panel_convert_inputLayout = new javax.swing.GroupLayout(panel_convert_input);
        panel_convert_input.setLayout(panel_convert_inputLayout);
        panel_convert_inputLayout.setHorizontalGroup(
            panel_convert_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_convert_inputLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(panel_convert_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_convert_inputLayout.createSequentialGroup()
                        .addComponent(leftSymbol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leftAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(leftDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        panel_convert_inputLayout.setVerticalGroup(
            panel_convert_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_convert_inputLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(leftDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_convert_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftSymbol))
                .addGap(63, 63, 63))
        );

        panel_convert_output.setBackground(new java.awt.Color(32, 0, 96));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("£");

        rightDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentine Peso", "Australian Dollar", "Bahraini Dinar", "Botswana Pula", "Brazilian Real", "British Pound", "Bruneian Dollar", "Bulgarian Lev", "Canadian Dollar", "Chilean Peso", "Chinese Yuan Renminbi", "Colombian Peso", "Croatian Kuna", "Czech Koruna", "Danish Krone", "Emirati Dirham", "Euro", "Hong Kong Dollar", "Hungarian Forint", "Icelandic Krona", "Indian Rupee", "Indonesian Rupiah", "Iranian Rial", "Israeli Shekel", "Japanese Yen", "Kazakhstani Tenge", "Kuwaiti Dinar", "Libyan Dinar", "Malaysian Ringgit", "Mauritian Rupee", "Mexican Peso", "Nepalese Rupee", "New Zealand Dollar", "Norwegian Krone", "Omani Rial", "Pakistani Rupee", "Philippine Peso", "Polish Zloty", "Qatari Riyal", "Romanian New Leu", "Russian Ruble", "Saudi Arabian Riyal", "Singapore Dollar", "South African Rand", "South Korean Won", "Sri Lankan Rupee", "Swedish Krona", "Swiss Franc", "Taiwan New Dollar", "Thai Baht", "Trinidadian Dollar", "Turkish Lira", "US Dollar", "Venezuelan Bolivar" }));

        javax.swing.GroupLayout panel_convert_outputLayout = new javax.swing.GroupLayout(panel_convert_output);
        panel_convert_output.setLayout(panel_convert_outputLayout);
        panel_convert_outputLayout.setHorizontalGroup(
            panel_convert_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_convert_outputLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(panel_convert_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rightDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_convert_outputLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        panel_convert_outputLayout.setVerticalGroup(
            panel_convert_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_convert_outputLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rightDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_convert_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rightAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        panel_convert_buttons.setBackground(new java.awt.Color(32, 0, 96));

        button_swap.setText("↔");
        button_swap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_swapActionPerformed(evt);
            }
        });

        button_covert.setText("Convert");

        button_clear.setText("Clear");

        javax.swing.GroupLayout panel_convert_buttonsLayout = new javax.swing.GroupLayout(panel_convert_buttons);
        panel_convert_buttons.setLayout(panel_convert_buttonsLayout);
        panel_convert_buttonsLayout.setHorizontalGroup(
            panel_convert_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_convert_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_convert_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_swap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_covert, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(button_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_convert_buttonsLayout.setVerticalGroup(
            panel_convert_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_convert_buttonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_swap)
                .addGap(18, 18, 18)
                .addComponent(button_covert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_clear)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout panel_converterLayout = new javax.swing.GroupLayout(panel_converter);
        panel_converter.setLayout(panel_converterLayout);
        panel_converterLayout.setHorizontalGroup(
            panel_converterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_converterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_convert_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(panel_convert_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_convert_output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_converterLayout.setVerticalGroup(
            panel_converterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_converterLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(panel_converterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_convert_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_convert_output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_convert_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Converter", panel_converter);

        javax.swing.GroupLayout panel_historyLayout = new javax.swing.GroupLayout(panel_history);
        panel_history.setLayout(panel_historyLayout);
        panel_historyLayout.setHorizontalGroup(
            panel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        panel_historyLayout.setVerticalGroup(
            panel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("History", panel_history);

        jMenu1.setText("File");

        menuItem_Exit.setText("Exit");
        menuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_Exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItem_ExitActionPerformed

    private void button_swapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_swapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_swapActionPerformed

    
    //This method replaces the text in the left text box with s
    void setLeftVal(String s) {
        leftAmount.setText(s);
    }

    
    //This method replaces the value of the drop down with s
    void setLeftDropDown(String s) {
        for (int i = 0; i < leftDropDown.getItemCount(); i++) {
            if (leftDropDown.getItemAt(i).equals(s)) {
                leftDropDown.setSelectedIndex(i);
            }
        }
    }

    
    //This method replaces the value of the right text box with s
    void setRightVal(String s) {
        rightAmount.setText(s);
    }

    //This method replaces the value of the right drop down with s
    void setRightDropDown(String s) {
        for (int i = 0; i < rightDropDown.getItemCount(); i++) {
            if (rightDropDown.getItemAt(i).equals(s)) {
                rightDropDown.setSelectedIndex(i);
            }
        }
    }

    
    //This method returns what is currently stored in the left text box
    String getLeftText() {
      return leftAmount.getText();
    }

    
    //This method returns what is currently stored in the right drop down
    String getRightDropDown() {
        return rightDropDown.getSelectedItem().toString();
    }

    
    //This method returns what is currently stored 
    String getLeftDropDown() {
        return leftDropDown.getSelectedItem().toString();
    }    
    
    
    
    
    private Controller c = new Controller();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_clear;
    private javax.swing.JButton button_covert;
    private javax.swing.JButton button_swap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField leftAmount;
    private javax.swing.JComboBox<String> leftDropDown;
    private javax.swing.JLabel leftSymbol;
    private javax.swing.JMenuItem menuItem_Exit;
    private javax.swing.JPanel panel_convert_buttons;
    private javax.swing.JPanel panel_convert_input;
    private javax.swing.JPanel panel_convert_output;
    private javax.swing.JPanel panel_converter;
    private javax.swing.JPanel panel_history;
    private javax.swing.JPanel panel_user;
    private javax.swing.JTextField rightAmount;
    private javax.swing.JComboBox<String> rightDropDown;
    // End of variables declaration//GEN-END:variables
    private static String[] currency_symbols = {"$", "£", "€", "¥", "¥"};
}
