/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc4380;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import static javax.swing.SwingConstants.CENTER;

/**
 *
 * @author aaron
 */
public class View extends javax.swing.JFrame {


    /**
     * Creates new form View
     */
    public View(Controller controller) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.initUI();
        this.initListeners();
        dialog_edit.setLocationRelativeTo(null);
        this.lockProfile();
        c = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_edit = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        drop_native = new javax.swing.JComboBox<>();
        button_submit = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_user = new javax.swing.JPanel();
        panel_signup = new javax.swing.JPanel();
        label_signup = new javax.swing.JLabel();
        textField_signup_user = new javax.swing.JTextField();
        button_signup = new javax.swing.JButton();
        label_signup_user = new javax.swing.JLabel();
        label_signup_pass = new javax.swing.JLabel();
        textField_signup_pass = new javax.swing.JPasswordField();
        panel_login = new javax.swing.JPanel();
        label_login = new javax.swing.JLabel();
        label_login_user = new javax.swing.JLabel();
        textField_login_user = new javax.swing.JTextField();
        label_login_pass = new javax.swing.JLabel();
        button_login = new javax.swing.JButton();
        textField_login_pass = new javax.swing.JPasswordField();
        panel_vert_separator = new javax.swing.JPanel();
        status_field = new javax.swing.JLabel();
        panel_converter = new javax.swing.JPanel();
        panel_convert_input = new javax.swing.JPanel();
        leftAmount = new javax.swing.JTextField();
        leftDropDown = new javax.swing.JComboBox<>();
        panel_convert_output = new javax.swing.JPanel();
        rightAmount = new javax.swing.JTextField();
        rightDropDown = new javax.swing.JComboBox<>();
        panel_convert_buttons = new javax.swing.JPanel();
        button_swap = new javax.swing.JButton();
        button_convert = new javax.swing.JButton();
        button_clear = new javax.swing.JButton();
        panel_history = new javax.swing.JPanel();
        label_username = new javax.swing.JLabel();
        label_native_country = new javax.swing.JLabel();
        label_country = new javax.swing.JLabel();
        button_edit = new javax.swing.JButton();
        label_last = new javax.swing.JLabel();
        label_last_conver = new javax.swing.JLabel();
        button_delete = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItem_Exit = new javax.swing.JMenuItem();

        jPanel1.setBackground(new java.awt.Color(32, 0, 96));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Native Country:");

        drop_native.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Australia", "Bahrain", "Botswana", "Brazil", "Britain", "Brunei", "Bulgaria", "Canada", "Chile", "China", "Colombia", "Croatia", "Czech", "Denmark", "Emirate", "European Region", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Israel", "Japan", "Kazakhstan", "Kuwait", "Libya", "Malaysia", "Mauritius", "Mexico", "Nepal", "New Zealand", "Norwegia", "Oman", "Pakistan", "Philippines", "Poland", "Qatar", "Romania", "Russia", "Saudi Arabia", "Singapore", "South Africa", "South Korea", "Sri Lanka", "Sweden", "Switzerland", "Taiwan", "Thailand", "Trinidad", "Turkey", "United States", "Venezuela" }));

        button_submit.setText("Submit");
        button_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_submitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(drop_native, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_submit)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(drop_native, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(button_submit)
                .addContainerGap())
        );

        javax.swing.GroupLayout dialog_editLayout = new javax.swing.GroupLayout(dialog_edit.getContentPane());
        dialog_edit.getContentPane().setLayout(dialog_editLayout);
        dialog_editLayout.setHorizontalGroup(
            dialog_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialog_editLayout.setVerticalGroup(
            dialog_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 25, 140));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        panel_user.setBackground(new java.awt.Color(32, 0, 96));

        panel_signup.setBackground(new java.awt.Color(255, 255, 255));
        panel_signup.setOpaque(false);
        panel_signup.setPreferredSize(new java.awt.Dimension(300, 350));

        label_signup.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_signup.setForeground(new java.awt.Color(255, 255, 255));
        label_signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_signup.setText("Signup");

        textField_signup_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField_signup_user.setForeground(new java.awt.Color(255, 255, 255));
        textField_signup_user.setBorder(null);
        textField_signup_user.setOpaque(false);
        textField_signup_user.setPreferredSize(new java.awt.Dimension(100, 40));

        button_signup.setBackground(new java.awt.Color(0, 25, 140));
        button_signup.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        button_signup.setForeground(new java.awt.Color(255, 255, 255));
        button_signup.setText("Signup");
        button_signup.setBorder(null);
        button_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_signupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_signupMouseExited(evt);
            }
        });

        label_signup_user.setForeground(new java.awt.Color(255, 255, 255));
        label_signup_user.setText("Username");

        label_signup_pass.setForeground(new java.awt.Color(255, 255, 255));
        label_signup_pass.setText("Password");

        textField_signup_pass.setForeground(new java.awt.Color(255, 255, 255));
        textField_signup_pass.setBorder(null);
        textField_signup_pass.setOpaque(false);

        javax.swing.GroupLayout panel_signupLayout = new javax.swing.GroupLayout(panel_signup);
        panel_signup.setLayout(panel_signupLayout);
        panel_signupLayout.setHorizontalGroup(
            panel_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_signupLayout.createSequentialGroup()
                .addGroup(panel_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textField_signup_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_signupLayout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(button_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_signupLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(label_signup_user, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_signupLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(textField_signup_user, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_signupLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(label_signup_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panel_signupLayout.setVerticalGroup(
            panel_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_signupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_signup)
                .addGap(37, 37, 37)
                .addComponent(label_signup_user, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_signup_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_signup_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_signup_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        panel_login.setBackground(new java.awt.Color(51, 0, 153));
        panel_login.setOpaque(false);
        panel_login.setPreferredSize(new java.awt.Dimension(300, 350));

        label_login.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_login.setForeground(new java.awt.Color(255, 255, 255));
        label_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_login.setText("Login");

        label_login_user.setForeground(new java.awt.Color(255, 255, 255));
        label_login_user.setText("Username");

        textField_login_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField_login_user.setForeground(new java.awt.Color(255, 255, 255));
        textField_login_user.setBorder(null);
        textField_login_user.setOpaque(false);
        textField_login_user.setPreferredSize(new java.awt.Dimension(100, 40));

        label_login_pass.setForeground(new java.awt.Color(255, 255, 255));
        label_login_pass.setText("Password");

        button_login.setBackground(new java.awt.Color(0, 25, 140));
        button_login.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        button_login.setForeground(new java.awt.Color(255, 255, 255));
        button_login.setText("Login");
        button_login.setBorder(null);
        button_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_loginMouseExited(evt);
            }
        });

        textField_login_pass.setForeground(new java.awt.Color(255, 255, 255));
        textField_login_pass.setBorder(null);
        textField_login_pass.setOpaque(false);

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textField_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_loginLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_loginLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(label_login_user, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textField_login_user, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(60, Short.MAX_VALUE)))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(textField_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_loginLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(label_login_user, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(textField_login_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(label_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(65, 65, 65)
                    .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(70, Short.MAX_VALUE)))
        );

        panel_vert_separator.setBackground(new java.awt.Color(0, 51, 153));
        panel_vert_separator.setPreferredSize(new java.awt.Dimension(5, 350));

        javax.swing.GroupLayout panel_vert_separatorLayout = new javax.swing.GroupLayout(panel_vert_separator);
        panel_vert_separator.setLayout(panel_vert_separatorLayout);
        panel_vert_separatorLayout.setHorizontalGroup(
            panel_vert_separatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        panel_vert_separatorLayout.setVerticalGroup(
            panel_vert_separatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        status_field.setBackground(new java.awt.Color(255, 153, 153));
        status_field.setForeground(new java.awt.Color(255, 255, 255));
        status_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_userLayout = new javax.swing.GroupLayout(panel_user);
        panel_user.setLayout(panel_userLayout);
        panel_userLayout.setHorizontalGroup(
            panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_userLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_userLayout.createSequentialGroup()
                        .addComponent(status_field, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_userLayout.createSequentialGroup()
                        .addComponent(panel_signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(panel_vert_separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        panel_userLayout.setVerticalGroup(
            panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status_field, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_vert_separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User", panel_user);

        panel_converter.setBackground(new java.awt.Color(32, 0, 96));

        panel_convert_input.setBackground(new java.awt.Color(32, 0, 96));

        leftAmount.setBackground(new java.awt.Color(51, 0, 153));
        leftAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        leftAmount.setForeground(new java.awt.Color(255, 255, 255));
        leftAmount.setText("1.00");
        leftAmount.setBorder(null);
        leftAmount.setOpaque(false);

        leftDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentine Peso", "Australian Dollar", "Bahraini Dinar", "Botswana Pula", "Brazilian Real", "British Pound", "Bruneian Dollar", "Bulgarian Lev", "Canadian Dollar", "Chilean Peso", "Chinese Yuan Renminbi", "Colombian Peso", "Croatian Kuna", "Czech Koruna", "Danish Krone", "Emirati Dirham", "Euro", "Hong Kong Dollar", "Hungarian Forint", "Icelandic Krona", "Indian Rupee", "Indonesian Rupiah", "Iranian Rial", "Israeli Shekel", "Japanese Yen", "Kazakhstani Tenge", "Kuwaiti Dinar", "Libyan Dinar", "Malaysian Ringgit", "Mauritian Rupee", "Mexican Peso", "Nepalese Rupee", "New Zealand Dollar", "Norwegian Krone", "Omani Rial", "Pakistani Rupee", "Philippine Peso", "Polish Zloty", "Qatari Riyal", "Romanian New Leu", "Russian Ruble", "Saudi Arabian Riyal", "Singapore Dollar", "South African Rand", "South Korean Won", "Sri Lankan Rupee", "Swedish Krona", "Swiss Franc", "Taiwan New Dollar", "Thai Baht", "Trinidadian Dollar", "Turkish Lira", "US Dollar", "Venezuelan Bolivar" }));
        leftDropDown.setSelectedIndex(52);
        leftDropDown.setBorder(null);

        javax.swing.GroupLayout panel_convert_inputLayout = new javax.swing.GroupLayout(panel_convert_input);
        panel_convert_input.setLayout(panel_convert_inputLayout);
        panel_convert_inputLayout.setHorizontalGroup(
            panel_convert_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_convert_inputLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_convert_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(leftDropDown, 0, 170, Short.MAX_VALUE)
                    .addComponent(leftAmount))
                .addGap(63, 63, 63))
        );
        panel_convert_inputLayout.setVerticalGroup(
            panel_convert_inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_convert_inputLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(leftDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(leftAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        panel_convert_output.setBackground(new java.awt.Color(32, 0, 96));

        rightAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rightAmount.setForeground(new java.awt.Color(255, 255, 255));
        rightAmount.setText("0.76");
        rightAmount.setBorder(null);
        rightAmount.setOpaque(false);
        rightAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightAmountActionPerformed(evt);
            }
        });

        rightDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentine Peso", "Australian Dollar", "Bahraini Dinar", "Botswana Pula", "Brazilian Real", "British Pound", "Bruneian Dollar", "Bulgarian Lev", "Canadian Dollar", "Chilean Peso", "Chinese Yuan Renminbi", "Colombian Peso", "Croatian Kuna", "Czech Koruna", "Danish Krone", "Emirati Dirham", "Euro", "Hong Kong Dollar", "Hungarian Forint", "Icelandic Krona", "Indian Rupee", "Indonesian Rupiah", "Iranian Rial", "Israeli Shekel", "Japanese Yen", "Kazakhstani Tenge", "Kuwaiti Dinar", "Libyan Dinar", "Malaysian Ringgit", "Mauritian Rupee", "Mexican Peso", "Nepalese Rupee", "New Zealand Dollar", "Norwegian Krone", "Omani Rial", "Pakistani Rupee", "Philippine Peso", "Polish Zloty", "Qatari Riyal", "Romanian New Leu", "Russian Ruble", "Saudi Arabian Riyal", "Singapore Dollar", "South African Rand", "South Korean Won", "Sri Lankan Rupee", "Swedish Krona", "Swiss Franc", "Taiwan New Dollar", "Thai Baht", "Trinidadian Dollar", "Turkish Lira", "US Dollar", "Venezuelan Bolivar" }));
        rightDropDown.setSelectedIndex(5);
        rightDropDown.setBorder(null);

        javax.swing.GroupLayout panel_convert_outputLayout = new javax.swing.GroupLayout(panel_convert_output);
        panel_convert_output.setLayout(panel_convert_outputLayout);
        panel_convert_outputLayout.setHorizontalGroup(
            panel_convert_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_convert_outputLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(panel_convert_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rightDropDown, 0, 170, Short.MAX_VALUE)
                    .addComponent(rightAmount))
                .addGap(53, 53, 53))
        );
        panel_convert_outputLayout.setVerticalGroup(
            panel_convert_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_convert_outputLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(rightDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rightAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        panel_convert_buttons.setBackground(new java.awt.Color(32, 0, 96));

        button_swap.setBackground(new java.awt.Color(0, 25, 140));
        button_swap.setForeground(new java.awt.Color(255, 255, 255));
        button_swap.setText("↔");
        button_swap.setBorder(null);
        button_swap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_swapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_swapMouseExited(evt);
            }
        });

        button_convert.setBackground(new java.awt.Color(0, 25, 140));
        button_convert.setForeground(new java.awt.Color(255, 255, 255));
        button_convert.setText("Convert");
        button_convert.setBorder(null);
        button_convert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_convertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_convertMouseExited(evt);
            }
        });

        button_clear.setBackground(new java.awt.Color(0, 25, 140));
        button_clear.setForeground(new java.awt.Color(255, 255, 255));
        button_clear.setText("Clear");
        button_clear.setBorder(null);
        button_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_clearMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_convert_buttonsLayout = new javax.swing.GroupLayout(panel_convert_buttons);
        panel_convert_buttons.setLayout(panel_convert_buttonsLayout);
        panel_convert_buttonsLayout.setHorizontalGroup(
            panel_convert_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_convert_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_convert_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_swap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_convert, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(button_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_convert_buttonsLayout.setVerticalGroup(
            panel_convert_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_convert_buttonsLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(button_swap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_convert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_converterLayout = new javax.swing.GroupLayout(panel_converter);
        panel_converter.setLayout(panel_converterLayout);
        panel_converterLayout.setHorizontalGroup(
            panel_converterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_converterLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(panel_convert_input, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(panel_convert_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(panel_convert_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        panel_converterLayout.setVerticalGroup(
            panel_converterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_converterLayout.createSequentialGroup()
                .addGroup(panel_converterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_converterLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(panel_converterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_convert_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_convert_output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_converterLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(panel_convert_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Converter", panel_converter);

        panel_history.setBackground(new java.awt.Color(32, 0, 96));

        label_username.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        label_username.setForeground(new java.awt.Color(255, 255, 255));
        label_username.setText("placeholder");

        label_native_country.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_native_country.setForeground(new java.awt.Color(255, 255, 255));
        label_native_country.setText("Native Country:");

        label_country.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_country.setForeground(new java.awt.Color(255, 255, 255));
        label_country.setText("country");

        button_edit.setBackground(new java.awt.Color(0, 25, 140));
        button_edit.setForeground(new java.awt.Color(255, 255, 255));
        button_edit.setText("Edit Profile");
        button_edit.setToolTipText("");
        button_edit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                button_editMouseDragged(evt);
            }
        });
        button_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_editMouseEntered(evt);
            }
        });

        label_last.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_last.setForeground(new java.awt.Color(255, 255, 255));
        label_last.setText("Last Conversion:");

        label_last_conver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_last_conver.setForeground(new java.awt.Color(255, 255, 255));
        label_last_conver.setText("country");

        button_delete.setBackground(new java.awt.Color(0, 25, 140));
        button_delete.setForeground(new java.awt.Color(255, 255, 255));
        button_delete.setText("Delete");
        button_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_deleteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_historyLayout = new javax.swing.GroupLayout(panel_history);
        panel_history.setLayout(panel_historyLayout);
        panel_historyLayout.setHorizontalGroup(
            panel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_historyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_delete)
                .addGap(18, 18, 18)
                .addComponent(button_edit)
                .addContainerGap())
            .addGroup(panel_historyLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_historyLayout.createSequentialGroup()
                        .addComponent(label_last)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_last_conver))
                    .addGroup(panel_historyLayout.createSequentialGroup()
                        .addComponent(label_native_country)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_country))
                    .addComponent(label_username))
                .addContainerGap(573, Short.MAX_VALUE))
        );
        panel_historyLayout.setVerticalGroup(
            panel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_historyLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(label_username)
                .addGap(34, 34, 34)
                .addGroup(panel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_native_country)
                    .addComponent(label_country))
                .addGap(18, 18, 18)
                .addGroup(panel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_last)
                    .addComponent(label_last_conver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addGroup(panel_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_edit)
                    .addComponent(button_delete))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Profile", panel_history);

        jMenu1.setText("File");

        menuItem_Exit.setText("Exit");
        menuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_Exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItem_ExitActionPerformed

    private void button_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signupMouseClicked
        jTabbedPane1.setEnabledAt(2,false);
    }//GEN-LAST:event_button_signupMouseClicked

    private void button_signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signupMouseEntered
        hover(button_signup);
    }//GEN-LAST:event_button_signupMouseEntered

    private void button_signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_signupMouseExited
        stopHover(button_signup);
    }//GEN-LAST:event_button_signupMouseExited

    private void button_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseEntered
        hover(button_login);
    }//GEN-LAST:event_button_loginMouseEntered

    private void button_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseExited
        stopHover(button_login);
    }//GEN-LAST:event_button_loginMouseExited


    private void button_swapMouseEntered(java.awt.event.MouseEvent evt) {                                         
        hover(button_swap);
    }                                        

    private void button_swapMouseExited(java.awt.event.MouseEvent evt) {                                        
        stopHover(button_swap);
    }                                       

    private void button_convertMouseEntered(java.awt.event.MouseEvent evt) {                                            
        hover(button_convert);
    }                                           

    private void button_convertMouseExited(java.awt.event.MouseEvent evt) {                                           
        stopHover(button_convert);
    }                                          

    private void button_clearMouseEntered(java.awt.event.MouseEvent evt) {                                          
        hover(button_clear);
    }                                         
    private void button_clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_clearMouseExited
        stopHover(button_clear);
    }//GEN-LAST:event_button_clearMouseExited

    private void rightAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightAmountActionPerformed

    private void button_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_editMouseClicked
        dialog_edit.pack();
        dialog_edit.setVisible(true);
    }//GEN-LAST:event_button_editMouseClicked

    private void button_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_submitMouseClicked
        country = drop_native.getSelectedItem().toString();
        dialog_edit.setVisible(false);
        label_country.setText(country);
        c.btnEditProf(this);
    }//GEN-LAST:event_button_submitMouseClicked

    private void button_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_deleteMouseEntered
        hover(button_delete);
    }//GEN-LAST:event_button_deleteMouseEntered

    private void button_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_deleteMouseExited
        stopHover(button_delete);
    }//GEN-LAST:event_button_deleteMouseExited

    private void button_editMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_editMouseDragged
        hover(button_edit);
    }//GEN-LAST:event_button_editMouseDragged

    private void button_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_editMouseEntered
        stopHover(button_edit);
    }//GEN-LAST:event_button_editMouseEntered
    
    void initUI() {
        JTextField[] fields = {leftAmount, rightAmount, textField_signup_user, textField_signup_pass, textField_login_user, textField_login_pass};
        for (int i = 0; i < fields.length; i++) {
            fields[i].setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.WHITE));
            fields[i].setCaretColor(Color.WHITE);
        }
    }
    
    void initListeners() {
        button_convert.addActionListener(e -> c.btnConvert(this));
        button_swap.addActionListener(e -> c.btnSwap(this));
        button_clear.addActionListener(e -> c.btnClear(this));
        button_signup.addActionListener(e -> c.btnSignup(this));
        button_login.addActionListener(e -> c.btnLogin(this));
        button_delete.addActionListener(e -> c.btnDelete(this));
    }
    
    void hover(JButton b) {
        b.setBackground(hoverColor);
    }
    

    void stopHover(JButton b) {
        b.setBackground(baseColor);
    }
        
    
    //This method replaces the text in the left text box with s
    void setLeftVal(String s) {
        if(s.equals("")){
            leftAmount.setText("");
        } else
            leftAmount.setText(String.format("%.2f", Double.parseDouble(s)));
    }
    
    //This method replaces the value of the drop down with s
    void setLeftDropDown(String s) {
        for (int i = 0; i < leftDropDown.getItemCount(); i++) {
            if (leftDropDown.getItemAt(i).equals(s)) {
                leftDropDown.setSelectedIndex(i);
            }
        }
    }
    
    //This method replaces the value of the right text box with s
    void setRightVal(String s) {
        if(s.equals("")){
            rightAmount.setText("");
        } else
            rightAmount.setText(String.format("%.2f", Double.parseDouble(s)));
    }

    //This method replaces the value of the right drop down with s
    void setRightDropDown(String s) {
        for (int i = 0; i < rightDropDown.getItemCount(); i++) {
            if (rightDropDown.getItemAt(i).equals(s)) {
                rightDropDown.setSelectedIndex(i);
            }
        }
    }
    
    //This method returns what is currently stored in the left text box
    String getLeftText() {
      return leftAmount.getText();
    }
    
    //This method returns what is currently stored in the right drop down
    String getRightDropDown() {
        return rightDropDown.getSelectedItem().toString();
    }
    
    //This method returns what is currently stored 
    String getLeftDropDown() {
        return leftDropDown.getSelectedItem().toString();
    }
    
    String getLeftUserName() {
        return label_signup_user.getText();
    }
    
    String getRightUserName() {
        return label_login_user.getText();
    }
    
    String getLeftPassword() {
        return label_signup_pass.getText();
    }
    
    String getRightPassword() {
        return label_login_pass.getText();
    }

    
    String getSignUpUser() {
        return textField_signup_user.getText();
    }
    
    String getSignUpPass() {
        return new String(textField_signup_pass.getPassword());
    }
    
    String getLoginUser() {
        return textField_login_user.getText();
    }
    
    String getLoginPass() {
        return new String(textField_login_pass.getPassword());
    }
    
    void setStatus(String s) {
        if(s.equals("signup failed")) {
            status_field.setText("Signup Failed!");
            status_field.setBackground(new Color(255,153,153));
            status_field.setOpaque(true);
        } else if(s.equals("login success")) {
            status_field.setBackground(new Color(153,255,153));
            status_field.setText("Login Successful!");
            status_field.setOpaque(true);
        }else if(s.equals("login failed")) {
            status_field.setBackground(new Color(255,153,153));
            status_field.setText("Login Failed!");
            status_field.setOpaque(true);
        } else {
            status_field.setText("");
            status_field.setOpaque(false);
        }
        
    }
    
    void unlockProfile() {
        jTabbedPane1.setEnabledAt(2, true);
    }
    
    void lockProfile() {
        jTabbedPane1.setEnabledAt(2, false);
    }
    
    void loadUserInfo(String[] s) {
        label_username.setText(s[0]);
        label_country.setText(s[1]);
        label_last_conver.setText(s[2]);
    }
    
    void updateConver(String s) {
        label_last_conver.setText(s);
    }
    
    void goHome() {
        jTabbedPane1.setSelectedIndex(0);
        lockProfile();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_clear;
    private javax.swing.JButton button_convert;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_edit;
    private javax.swing.JButton button_login;
    private javax.swing.JButton button_signup;
    private javax.swing.JButton button_submit;
    private javax.swing.JButton button_swap;
    private javax.swing.JDialog dialog_edit;
    private javax.swing.JComboBox<String> drop_native;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_country;
    private javax.swing.JLabel label_last;
    private javax.swing.JLabel label_last_conver;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_login_pass;
    private javax.swing.JLabel label_login_user;
    private javax.swing.JLabel label_native_country;
    private javax.swing.JLabel label_signup;
    private javax.swing.JLabel label_signup_pass;
    private javax.swing.JLabel label_signup_user;
    private javax.swing.JLabel label_username;
    private javax.swing.JTextField leftAmount;
    private javax.swing.JComboBox<String> leftDropDown;
    private javax.swing.JMenuItem menuItem_Exit;
    private javax.swing.JPanel panel_convert_buttons;
    private javax.swing.JPanel panel_convert_input;
    private javax.swing.JPanel panel_convert_output;
    private javax.swing.JPanel panel_converter;
    private javax.swing.JPanel panel_history;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_signup;
    private javax.swing.JPanel panel_user;
    private javax.swing.JPanel panel_vert_separator;
    private javax.swing.JTextField rightAmount;
    private javax.swing.JComboBox<String> rightDropDown;
    private javax.swing.JLabel status_field;
    private javax.swing.JPasswordField textField_login_pass;
    private javax.swing.JTextField textField_login_user;
    private javax.swing.JPasswordField textField_signup_pass;
    private javax.swing.JTextField textField_signup_user;
    // End of variables declaration//GEN-END:variables
    private Controller c;
    private Color hoverColor = new Color(0,30,173);
    private Color baseColor = new Color(0,25,140);
    public String country;
    private String status;
}
